### PR TITLE
re-export parley && vello

### PR DESCRIPTION
**Pull request by ykerit**
I try to use masonry to implement my own application, which requires vello and parley

### CODE REVIEW

**Comment by DJMcNab** [comment]
Thanks for your interest!

I do think we'll probably want this, however, the same logic also applies elsewhere down the stack. This leads to there being lots of paths to the same item, which leads to a poor experience when using the crates.

E.g. you end up having `masonry::kurbo::Point` and `masonry::vello::kurbo::Point` and `masonry::parley::kurbo::Point`, and worse, you will likely end up using different paths in different imports.

Ideally there would be an easy way to avoid that, but we haven't worked that out yet. Suggestions welcome

See also #223, where I suggest deferring a similar question until after the upcoming conference.

**Comment by DJMcNab** [comment]
I've opened a [thread in the Zulip](https://xi.zulipchat.com/#narrow/stream/419691-linebender/topic/Re-exports.20policy/near/436130449) as an easier place to discuss solutions

**Comment by ykerit** [comment]
ok, looking forward to a better solution

**Review by DJMcNab — APPROVED** [review]
After some discussion in Zulip, I'm relatively happy to land this, recognising that we might rework this in future.

I'm not convinced by the `#[doc(inline)]` attribute; it has some pretty big disadvantages. E.g. it breaks [source links](https://docs.rs/druid/latest/druid/kurbo/struct.QuadBez.html) on docs.rs. Cc @xStrom , as you added the attribute causing this in https://github.com/linebender/druid/pull/733

Please remove the `doc(inline)` attribute from at least the new items, then we can land this. Thanks!

(I think for Vello, I'd prefer to re-export a smaller subset of their API, from the root, for example)

**Comment by simbleau** [comment]
Vello and Xilem should have a prelude for ergonomics, where these types live.

**Comment by ykerit** [comment]
> After some discussion in Zulip, I'm relatively happy to land this, recognising that we might rework this in future.
> 
> I'm not convinced by the `#[doc(inline)]` attribute; it has some pretty big disadvantages. E.g. it breaks [source links](https://docs.rs/druid/latest/druid/kurbo/struct.QuadBez.html) on docs.rs. Cc @xStrom , as you added the attribute causing this in [linebender/druid#733](https://github.com/linebender/druid/pull/733)
> 
> Please remove the `doc(inline)` attribute from at least the new items, then we can land this. Thanks!
> 
> (I think for Vello, I'd prefer to re-export a smaller subset of their API, from the root, for example)
Done, Already removed

**Comment by DJMcNab** [comment]
@ykerit what do you mean by this comment? https://github.com/linebender/xilem/pull/234#issuecomment-2085534725

**Comment by ykerit** [comment]
In the last line I mentioned that I have completed what you suggested  😂
@DJMcNab

**Pull request merged**
