### PR TITLE
Rename RootWidget::get_element to RootWidget::child_mut

### PR DESCRIPTION
**Pull request by PoignardAzur**

### CODE REVIEW

**Review by Philipp-M — APPROVED** [review]

**Comment by PoignardAzur** [comment]
Huh. It's weird the test fails. I did a rust-analyzer rename, it should have covered all uses.

**Comment by PoignardAzur** [comment]
Oh, it missed doc tests.

**Comment by Philipp-M** [comment]
Good that CI is catching this already :)

**Comment by Philipp-M** [comment]
> Oh, it missed doc tests.

Btw. relevant for this: https://github.com/rust-lang/rust-analyzer/issues/9573

**Pull request merged**
