### PR TITLE
xilem_web checkbox checked attr

### PR DESCRIPTION
**Pull request by burrbull**
Only `.attr("checked", None)` is valid value for unchecked.

### CODE REVIEW

**Comment by Philipp-M** [comment]
Hmm does something not work as expected?

There's:

```rust
impl IntoAttributeValue for bool {
    fn into_attr_value(self) -> Option<AttributeValue> {
        self.then_some(AttributeValue::True)
    }
}
```

So I believe this should result in the same?

**Comment by Philipp-M** [comment]
Generally we want to support the DOM attribute `HtmlInputElement::checked` at some time, to avoid hacks such as [this](https://github.com/linebender/xilem/blob/01cca4610c58761c06619ac5a8ff2d0fbdb36275/xilem_web/src/attribute.rs#L83).

**Comment by burrbull** [comment]
The issue is how browser processes "checked" attribute. Any value including "false" it is considering as "enabled".
Only absent attribute is "disabled".

**Comment by Philipp-M** [comment]
Yes I know that's why `AttributeValue::True` results in the attribute value `""` which is evaluated to true, while the boolean `false` removes that attribute alltogether. But this is a half-baked way to achieve this (as described in my previous comment)

**Pull request closed without merging**
