### PR TITLE
Make passes that affect accesskit nodes request an accessibility pass

### PR DESCRIPTION
**Pull request by PoignardAzur**

### CODE REVIEW

**Review by Philipp-M — APPROVED** [review]
LGTM.

**Review by DJMcNab — COMMENTED** [review]
Would it be worth having a mirror comment in the accessibility pass, so that changes there can be recognised?

**Comment by PoignardAzur** [comment]
Sure. Something along the line of "If a pass changes these attributes it should request accessibility"?

**Comment by DJMcNab** [comment]
Yeah, that sounds good.

**Pull request merged**
