### PR TITLE
xilem_web: Make MessageThunk public

### PR DESCRIPTION
**Pull request by flosse**

### CODE REVIEW

**Comment by flosse** [comment]
In order to send messages based on a JS callback, I need access to the `MessageThunk` to do something like this:

```rust
let thunk = ctx.message_thunk();
js_obj.on_event(move |ev|{
  let value = process_event(ev);
  thunk.push_message(JsMessage::Foo());
});
```

**Comment by Philipp-M** [comment]
Yeah I guess we can export that, but expect things to break in the future.

**Comment by flosse** [comment]
> Yeah I guess we can export that, but expect things to break in the future.

sure. But for now it would help in some situations :relaxed:

**Review by Philipp-M — APPROVED** [review]
Feel free to merge

**Pull request merged**
