### PR TITLE
Switch widget visual fixes

### PR DESCRIPTION
**Pull request by giannissc**
I have fixed the visuals of the knob in the hot (bigger and lighter), active (smaller and darker) and idle configuration.

The knob would also jump if the dragging started from the negative area of the widget and it seemed kinda jerky.

I have also disabled some of print statement in other places to cleanup the terminal output

### CODE REVIEW

**Comment by giannissc** [comment]
I have made another (final) PR for the switch widget with some last minute visual changes to it. I will be pushing the progress bar and slider next! @Philipp-M

**Comment by Philipp-M** [comment]
Hmm for me this regresses the dragging. Previously dragging with the mouse worked as expected, now it's kinda janky (it's much faster than the mouse pointer, and lags behind).

**Comment by giannissc** [comment]
Good catch. I rethought the implementation and it should be must smoother now. Let me know how you like it! @Philipp-M

**Review by nicoburns — APPROVED** [review]
Not sure if dragging is even really needed for the switch, but it's all working very smoothly for me with the latest version.

**Pull request merged**
