### PR TITLE
xilem_web: Apply props when the element type changes in `replace_inner`

### LINKED ISSUE #518: xilem_web: iframe `src` attribute not set after update
In this example, the `iframe` src attribute isn't set after clicking the button:

```rust
use xilem_web::{document_body, elements::html, interfaces::Element, App, DomView};

fn update(state: &mut bool) -> impl DomView<bool> {
    html::div((
        html::button("click me!").on_click(|state: &mut bool, _| *state = !*state),
        html::br(()),
        if *state {
            html::iframe(())
                .attr("src", "https://www.google.com")
                .boxed()
        } else {
            html::div("div!").boxed()
        },
    ))
}

fn main() {
    App::new(document_body(), false, update).run();
}
```

If the branches are swapped, the iframe `src` attribute is initially set, but unset after clicking the button twice.

### PR DESCRIPTION
**Pull request by Philipp-M**
Fixes #518

### CODE REVIEW

**Review by DJMcNab — APPROVED** [review]
Don't really know the context, but optimistic approval for Xilem Web

**Comment by Philipp-M** [comment]
(Attributes such as `src` in `<iframe src="..">` were not applied when changing the inner element (e.g. `<div>` -> `<iframe>`))

Thanks

**Comment by DJMcNab** [comment]
When I say the context here, I meant of why the change fixes that. But thanks, yeah

**Comment by Philipp-M** [comment]
Oh, ok, yeah it's basically, that the `ElementProps` are a virtual DOM version of the actual DOM representation and get updated in the modifier views. To actually change the DOM, `DomNode::apply_props` has to be run. This didn't happen when changing the inner element of an `AnyView`. The attributes are not applied in the type-erased version of the `Pod` (`AnyPod`), as... well the type of the props is erased, this happens before upcasting, or generally when erasing the type of the element.

**Pull request merged**
