### PR TITLE
Fix some small issues in the xilem_core view macros (hardcoded identifiers and missing ViewMarker for Box<dyn AnyView>)

### PR DESCRIPTION
**Pull request by Philipp-M**

### CODE REVIEW

**Review by raphlinus — COMMENTED** [review]
These changes look good to me, and I have some of it (the ViewSequence stuff) already in #62, which I'm more than happy to rebase. I know @derekdreery has also been working on this, and probably there's some overlap with #69, so want to check in about the best order.

**Comment by derekdreery** [comment]
Feel free to land yours first, I can rebase as needed.

**Review by derekdreery — APPROVED** [review]
LGTM

**Comment by raphlinus** [comment]
I can merge this if need be, but I've also sent an invite to Philipp, as "author merges" is our usual procedure.

**Pull request merged**
