### PR TITLE
Import Masonry crate

### PR DESCRIPTION
**Pull request by PoignardAzur**
This commit adds the `masonry` crate as-is to the repository. It doesn't integrate Xilem with Masonry in any way.

Masonry is a modular backend providing a Widget tree for GUI libraries, originally forked from the Druid project.

Previous history of this code is maintained in [the original Masonry repository](https://github.com/linebender/masonry). Explanations for design decisions may also be found in issues from [the Druid repository](https://github.com/linebender/druid).

### CODE REVIEW

**Review by Philipp-M — COMMENTED** [review]
Not sure how feasible a more in depth review is,
but I would probably add
```
"crates/masonry",
```
in `workspace.members` in the `Cargo.toml` at the root, so that it is possible to compile masonry. CI for masonry should run then too I guess.

**Comment by xStrom** [comment]
> Not sure how feasible a more in depth review is

Especially considering the time constraints we're operating under, I think we should be very liberal here and pretty much just merge. All fixes and adjustments can be follow-up PRs. That would also allow for more focused discussion over specific issues.

> CI for masonry should run then too

I wouldn't worry too much about CI. Xilem's own CI is a bit outdated right now, and Masonry has an even older version based on an old Druid script. Once this is merged I'll work on updating the Xilem CI to the latest Linebender standard, which would cover all crates, including Masonry.

**Review by DJMcNab — APPROVED** [review]
Approving, as I agree that making changes other than what was already in the masonry repository is not easy to review/verify.

If you're happy to squash, we can merge this once we have added the context to the PR description.

**Comment by PoignardAzur** [comment]
> Especially considering the time constraints we're operating under, I think we should be very liberal here and pretty much just merge. All fixes and adjustments can be follow-up PRs. That would also allow for more focused discussion over specific issues.

Agreed!

> I wouldn't worry too much about CI. Xilem's own CI is a bit outdated right now, and Masonry has an even older version based on an old Druid script. Once this is merged I'll work on updating the Xilem CI to the latest Linebender standard, which would cover all crates, including Masonry.

That would be great, I definitely haven't kept the CI config up to date. The only specificity to keep for now would be the `SKIP_RENDER_SNAPSHOTS` flag, until we get that wart removed.

> If you're happy to squash, we can merge this once we have added the context to the PR description.

Sure! Two questions:

- Does the mergue queue apply squash commits by default?
- How do we specify the commit messages?

**Comment by DJMcNab** [comment]
> Does the mergue queue apply squash commits by default?

Yes, the method is set to squash and merge in the branch protection settings.

> How do we specify the commit messages?

I'm not sure - but we can check what the message will be, if you give me a few minutes.

**Pull request merged**
