### PR TITLE
xilem_web: Add function to set HtmlIFrameElement src attribute

### PR DESCRIPTION
**Pull request by casey**
Apropos of #462. Let me know if this should have a test or an example!

### CODE REVIEW

**Comment by Philipp-M** [comment]
I don't think either is necessary (as this is a quite trivial change), having more examples, e.g. showing the "vision" of a more typed API is probably worth it anyway (I actually started something in #403, which is why there are a few methods in the interfaces traits, but that example was not optimal because of yet missing SSR).

I do think that should maybe be done in a separate PR though, maybe showing also other stuff like the `Box<AnyDomView>`.

What I think generally makes sense is to have some doc-comment examples, also serving as tests of the API, but I think in this case it's trivial, so I don't think necessary, that will be more interesting, when it's more than just a simple `impl IntoAttributeValue` as parameter, e.g. like with `Element::class`.

**Review by Philipp-M — APPROVED** [review]
LGTM

**Comment by casey** [comment]
I had a thought: Should the value of this attribute be a [Uri](https://docs.rs/http/latest/http/uri/struct.Uri.html)? It can't be a URL, because relative paths are allowed.

**Comment by Philipp-M** [comment]
Hmm, out of a typing perspective I think it should be.
I'm not sure, though, if we should have something like `impl IntoAttributeValue for Uri` instead, as HTML/DOM is so messy in its specification, and this will likely further increase boilerplate both in wasm binary size as well as visual, in the end it will be converted back to a string again anyway.

**Comment by Philipp-M** [comment]
Anyway, we can just go with this first, and do further adjustments of the (typed) API later I think. Merging, thanks.

**Pull request merged**
