### PR TITLE
Eliminate needless lifetimes

### PR DESCRIPTION
**Pull request by Philipp-M**
Result from `__CARGO_FIX_YOLO=1 cargo clippy --fix`.
As newest nightly clippy bleats about all of this.

### CODE REVIEW

**Comment by waywardmonkeys** [comment]
I've been avoiding doing this to any repo as I think it is worse and loses useful information.

I'd much rather just suppress it. There's an open issue in clippy about separating this or changing it as well.

**Comment by waywardmonkeys** [comment]
https://github.com/rust-lang/rust-clippy/issues/13514 is that issue.

**Comment by Philipp-M** [comment]
I see your point, though I think it's fine for all the cases in this PR though? But I have no strong opinion here...

**Comment by DJMcNab** [comment]
I don't really want to suppress this lint, because it does give useful results for e.g. functions.

That being said, these changes are also worse... https://github.com/rust-lang/rust-clippy/pull/13286 seems to just be an unfortunate breaking change.

**Review by flosse — APPROVED** [review]
I prefer to be as close to the default as possible, but am still in agreement with other styles :smile:

**Comment by Philipp-M** [comment]
> That being said, these changes are also worse...

You mean those in this PR?

So I think it comes down to sooner or later disable that lint or subdue to it (or add alternatives to clippy as suggested in this issue).

Should I merge this or close it?

**Comment by waywardmonkeys** [comment]
Will leave it up to Daniel but in the other repos, my inclination is to suppress this rather than do these sorts of changes. Hoping that it gets fixed upstream.

**Comment by DJMcNab** [comment]
If you're going to be running nightly, you should probably supress it locally until the story on the clippy side becomes clearer.

**Comment by Philipp-M** [comment]
Sure that's not the issue, I can suppress it locally. So rather close this PR for now? As at least two people *seem* to be opposed, and I don't *really* care, but I like less syntax if possible (without too much loss of information).

**Comment by DJMcNab** [comment]
I think so; we should see what decision is made on the clippy side first.

**Review by DJMcNab — APPROVED** [review]
I've changed my mind, I think these changes specifically are an improvement

**Comment by Philipp-M** [comment]
So I guess in anticipation to updating the Rust version I should merge this?

**Comment by DJMcNab** [comment]
Yeah, that would be good.

**Pull request merged**
