### PR TITLE
Import kurbo via vello, not glazier.

### PR DESCRIPTION
**Pull request by waywardmonkeys**
This makes this consistent in terms of where kurbo things are imported from.

### CODE REVIEW

**Review by jaredoconnell — APPROVED** [review]
This seems like a logical change to me. People will just need to keep an eye on the auto-imports if they use them.

**Comment by waywardmonkeys** [comment]
I had previously opened a discussion in Zulip about this: https://xi.zulipchat.com/#narrow/stream/354396-xilem/topic/Importing.20from.20kurbo

**Review by Philipp-M — APPROVED** [review]
Makes sense. Vello is semantically closer to kurbo than glazier and staying consistent here is a good idea. Thanks!

**Review by xStrom — APPROVED** [review]
Unifying imports is a good step towards reducing contributor confusion.

The crate sync issue can be handled in other ways and in a different PR, as also discussed in zulip.

**Pull request merged**
