### PR TITLE
fix: Update swash

### LINKED ISSUE #67: The example causes a panic in swash
I tried `cargo run` on Linux (NixOS) and this leads to this panic:

```sh
thread 'main' panicked at 'misaligned pointer dereference: address must be a multiple of 0x2 but is 0x556ae00cc02b', /home/mk/.cargo/git/checkouts/swash-cee884c7ebde3542/af0c735/src/internal/parse.rs:452:13
```

Commit: 4b403d3f53b94fde1dd99712af652b2dec0e43b9

### PR DESCRIPTION
**Pull request by flosse**
Fixes #67

### CODE REVIEW

**Comment by DJMcNab** [comment]
Thanks for the PR!

Should we actually have a `Cargo.lock` in this repository at all?
I wasn't aware we had it not ignored.

Also, this change is surprising - we shouldn't be able to change the rev just in the Cargo.lock - we should be depending on a specific `rev` instead.
I'll look into this more later.

So the first point isn't actionable, but feel free to investigate the second

**Comment by flosse** [comment]
> Should we actually have a `Cargo.lock` in this repository at all? I wasn't aware we had it not ignored.

Yes, a  `Cargo.lock` is very helpful to reproduce a behavior for an example/binary but I'd not use it for a library.
So it might be an idea to move the content of `src/` into a separate example folder so that it's clear.

 
> Also, this change is surprising - we shouldn't be able to change the rev just in the Cargo.lock - we should be depending on a specific `rev` instead.

I agree!

**Comment by flosse** [comment]
I moved `main.rs` now into an example folder. Fell free to do with this PR whatever you want, It's just a feedback from a random curious developer :wink:

**Comment by xStrom** [comment]
> Should we actually have a `Cargo.lock` in this repository at all?

Generally no. However right now we have it configured as an executable binary not just a library, and for an executable the `Cargo.lock` inclusion is common. For libraries (and indeed those who use the current `xilem` as a library) it is ignored anyway.

---

As for migrating from a binary to example instead, I would prefer if we didn't have so many files and nested folders. Which is to say, I don't think we need a `Cargo.toml` for the example, nor a `examples/basic/src/main.rs`. A simple `examples/hello.rs` should work fine.

**Comment by xStrom** [comment]
> Fell free to do with this PR whatever you want, It's just a feedback from a random curious developer 😉

We do appreciate the feedback. To be more precise of my own feedback to your feedback, it divides into two:
* To fix the actual swash problem, I think just updating `Cargo.lock` for now if it solves the issue for you, is a fine solution. I would approve & merge. (If modifying `Cargo.lock` solves it then the same problem doesn't propagate to people using `xilem` as a library.)
* We also want to move from bin to lib+examples, however I think this PR as it is right now needs modifications. Perhaps it's better to split that work into a different PR, or I can just submit a PR of my own as well. In any case, I don't want this to be a blocker for the original swash problem.

**Comment by flosse** [comment]
> * To fix the actual swash problem, I think just updating `Cargo.lock` for now if it solves the issue for you, is a fine solution.

:+1: 
 
> * We also want to move from bin to lib+examples, however I think this PR as it is right now needs modifications. Perhaps it's better to split that work into a different PR

:+1: 

I removed the last commit, so it's now only the update in `Cargo.lock` again.

**Review by xStrom — APPROVED** [review]
Thanks!

**Pull request merged**
