### PR TITLE
Disable hinting whilst a `VariableLabel` animation is ongoing

### PR DESCRIPTION
**Pull request by DJMcNab**
If using hinting during an animation, a shimmering effect can occur.

### CODE REVIEW

**Review by jaredoconnell — APPROVED** [review]
This fixes the choppiness that I was experiencing earlier. It works perfectly on Windows and Mac.

**Comment by DJMcNab** [comment]
Hmm, I'm surprised. I didn't think this had any impact on example directly... 
Are you sure you're still seeing the choppiness on main?

**Comment by jaredoconnell** [comment]
> Hmm, I'm surprised. I didn't think this had any impact on example directly... Are you sure you're still seeing the choppiness on main?

Ah. You are correct. In which case, I can confirm that I cannot spot any regressions in the example.

**Comment by DJMcNab** [comment]
Grand! No big surprises here, but this is the right behaviour. See also https://github.com/linebender/vello/issues/204 for the explanation of the shimmering.

This is more important once https://github.com/googlefonts/fontations/pull/1083 lands.

(@dfrg would it be useful for you if I hooked that up in Vello for testing?)

**Comment by dfrg** [comment]
> (@dfrg would it be useful for you if I hooked that up in Vello for testing?)

I appreciate the offer but that work is still in flux so it’s probably best to wait for a release.

**Pull request merged**
