### PR TITLE
Fix typos.

### PR DESCRIPTION
**Pull request by waywardmonkeys**

### CODE REVIEW

**Review by Philipp-M — APPROVED** [review]

**Comment by derekdreery** [comment]
Hey @waywardmonkeys I'll merge this PR, but if you'd like to merge your own PRs after review, let us know and someone will give you write permission.

**Comment by waywardmonkeys** [comment]
> Hey @waywardmonkeys I'll merge this PR, but if you'd like to merge your own PRs after review, let us know and someone will give you write permission.

I think I have it already!

**Comment by jplatte** [comment]
https://github.com/crate-ci/typos would have also caught all of these! I'll create another PR with further typo fixes and a CI job for it.

**Comment by waywardmonkeys** [comment]
> https://github.com/crate-ci/typos would have also caught all of these (maybe it was used to find them?). I'll create another PR with further typo fixes and a CI job for it.

Yeah, that was how I found them this time and I figured the next step was to resolve anything else and then do the CI step. You're welcome to though if you want! :)

> edit: Hm, actually the only other thing it finds is "seeked" which is not an actual word but I'm not sure whether to set it to ignore, or whether it should be changed..

Yes ... I kind of like the idea of using "Sought" there. But that's why I left it for another step.

**Pull request merged**
