### PR TITLE
xilem_web: Add fetch example

### PR DESCRIPTION
**Pull request by flosse**
I was wondering what the integration of asynchronous calls looks like.
Here is an example, which works, but everything is more like a dirty hack.

Therefore, this PR should first serve as a basis for discussion.

### CODE REVIEW

**Comment by DJMcNab** [comment]
If at all practical, this should try and use APIs similar to those in #423

**Comment by flosse** [comment]
> If at all practical, this should try and use APIs similar to those in #423

Thank you for the hint!
I'll take a closer look at that.

**Comment by flosse** [comment]
My first question on the subject is what the **API** should ideally look like.
If I understand the example in #423 correctly, a pseudo view element is created which executes an asynchronous context:

https://github.com/linebender/xilem/blob/79bc28c6f6e5945cde180d599c47e9c2c568356b/xilem/examples/mason.rs#L71-L82<

But how could a async task be executed that was triggered by an event?

```rust
div(()).on_click(|state, event|{
   // TODO: how to spawn an async task and process the outcome?
})
```
Return a task/command with the future and an update function?
```rust
div(()).on_click(|state, event|{
    let task = async move {
        do_something().await
    };
    Command::AsyncTask(task, |state, output|{
        state.value = output;
    })
})
```

**Comment by Philipp-M** [comment]
> But how could a async task be executed that was triggered by an event?

I see two ways currently to deal with that:

1. Similar as I have done that with an `EventHandler` trait (which is basically a `View` so it may or may not be just an "event" `View`, with an additional generic parameter for the `Event` type), which allows more flexibility for dealing with events, as already linked in that PR, like [this](https://github.com/Philipp-M/trui/blob/dd24a2921eb0587dfffbbafea4a3e62b92f39c43/examples/async_event_handler_stream.rs#L67-L82)
2. Similar as you have already shown, via an `Action` type (doesn't need to be necessarily an enum though), which is composed within a handler-view that handles the returned action.

I slightly lean to 1. as it's less boilerplate and I think looks a little bit cleaner and less convoluted (and in my eyes more idiomatic), but it's not 100% optimal with inference in rust-analyzer currently, and *may* create more complex errors.

A third, but in my eyes not ideal option (because not that straight-forward and convoluted), would be to have a flag that is set in the event-callback, which in turn inserts such a pseudo-view in the view-tree (like `fork(..,Some(run_once()))`).

**Comment by flosse** [comment]
> 1. Similar as I have done that with an `EventHandler` trait (which is basically a `View` so it may or may not be just an "event" `View`, with an additional generic parameter for the `Event` type), which allows more flexibility for dealing with events, as already linked in that PR, like [this](https://github.com/Philipp-M/trui/blob/dd24a2921eb0587dfffbbafea4a3e62b92f39c43/examples/async_event_handler_stream.rs#L67-L82)

As a novice and from a user's point of view, this looks like a very intuitive and elegant solution to me :+1: 
I will definitely take a closer look at your approach.

**Comment by DJMcNab** [comment]
A composed async action handler is a really neat idea!

**Comment by DJMcNab** [comment]
As a note on my philosophy for this async work - I really want to try and keep the async work declarative if at all possible - that has some really nice properties around cancellation and similar.

**Comment by Philipp-M** [comment]
> A composed async action handler is a really neat idea!

Just for clarification, do you mean my first or my second point?

> As a note on my philosophy for this async work - I really want to try and keep the async work declarative if at all possible

I think we're aligned in this.

**Comment by flosse** [comment]
I started playing with the EventHandler trait idea, but got stuck in a few places.
Unfortunately I'm away for a week now but will come back to it afterwards.

**Comment by DJMcNab** [comment]
> Just for clarification, do you mean my first or my second point?

The second point.

**Comment by Philipp-M** [comment]
@flosse I think you may be interested in #440 which does now implement the first of my points

**Comment by flosse** [comment]
I am closing this PR in favor of #440 and #448.
Thanks @Philipp-M for taking up this topic!

**Pull request closed without merging**
