### PR TITLE
clippy: Miscellaneous fixes.

### PR DESCRIPTION
**Pull request by waywardmonkeys**

### CODE REVIEW

**Comment by waywardmonkeys** [comment]
This gets us closer to no errors / warnings from clippy so that we can eventually enable it in CI.

**Review by Philipp-M — APPROVED** [review]
Looks good, thanks (have thought about adding this myself, but you were faster :))

**Comment by waywardmonkeys** [comment]
@Philipp-M There are still things left to fix (for another PR), so you have another shot! :)

**Comment by Philipp-M** [comment]
Yeah for sure, there are also quite a few things that are more interesting than clippy fixes ^^

**Pull request merged**
