### PR TITLE
Add initial accessibility support

### PR DESCRIPTION
**Pull request by PoignardAzur**
Add AccessKit dependency.
Add accesskit_winit dependency.
Add methods to the Widget trait which create the accessibility tree and react to accessibility events.

### CODE REVIEW

**Comment by PoignardAzur** [comment]
Note that accessibility events are still missing. I'm hoping to get them done before office hours today.

**Comment by mwcampbell** [comment]
I suggest you drop the new `app_name` method from `AppDriver` and don't set `app_name` on `accesskit::Tree`. Requiring every application to explicitly provide an app name adds to the boilerplate, and I don't think it's justified. Only AT-SPI has an app name property in the first place, and strictly speaking, it's not needed. I'm having second thoughts anyway about whether AccessKit should have such a property; our AT-SPI backend could set it from the executable name, after all.

**Comment by mwcampbell** [comment]
Are we always going to require every application to directly create its winit window, as I'm seeing in the Masonry examples? If so, that's going to make it inconvenient to implement accessibility correctly, and very easy to get it wrong, as the examples currently do. As documented in `accesskit_winit` and shown in that crate's examples, it's necessary to create the window invisible, then create the AccessKit adapter, then show the window. Creating the window initially visible (the default) and then creating the AccessKit adapter doesn't work reliably on Windows. I haven't tested that case on macOS.

**Comment by mwcampbell** [comment]
Calling `accesskit_winit::Adapter::process_event` for every `WindowEvent`, as shown in the `accesskit_winit` examples, is absolutely necessary on macOS and Linux.

**Comment by mwcampbell** [comment]
I see that `accesskit_winit::Adapter::update_if_active` is being called for the initial tree, but not for subsequent updates. Is that what you meant by accessibility events being missing? I assumed that was referring to action requests.

**Comment by mwcampbell** [comment]
It looks like `root_accessibility` leaves the role of the root node at the default, which is `Role::Unknown`. It should be `Role::Window`.

**Comment by PoignardAzur** [comment]
> I suggest you drop the new app_name method from AppDriver and don't set app_name on accesskit::Tree

Done.

> Are we always going to require every application to directly create its winit window, as I'm seeing in the Masonry examples?

I'd like the default workflow to be "Provide WindowAttributes to Masonry, Masonry creates the window".

> I see that accesskit_winit::Adapter::update_if_active is being called for the initial tree, but not for subsequent updates.

Fixed in last commit.

> It looks like `root_accessibility` leaves the role of the root node at the default, which is `Role::Unknown`. It should be `Role::Window`.

Actually, the one place where `NodeBuilder::default` is called creates kind of a fake "parent of the root" node. That node is never added to accessibility tree.

I can set `Role::Window` in the xilem root widget, though.

**Comment by PoignardAzur** [comment]
> Calling `accesskit_winit::Adapter::process_event` for every `WindowEvent`, as shown in the `accesskit_winit` examples, is absolutely necessary on macOS and Linux.

Done.

> If so, that's going to make it inconvenient to implement accessibility correctly, and very easy to get it wrong, as the examples currently do. As documented in `accesskit_winit` and shown in that crate's examples, it's necessary to create the window invisible, then create the AccessKit adapter, then show the window.

Done.

**Comment by mwcampbell** [comment]
In widget containers or wrappers, it's incorrect for `accessibility_role` to return `Role::GenericContainer` while `accessibility` simply forwards the call to the child/inner widget. That would lead to a single accessibility node with a role of `GenericContainer` but other properties from the child widget. In other words, the correct accessibility role from the child widget wouldn't be set. You have to either forward the call to `accessibility_role` to the child as well, or the parent's `accessibility` method has to push a child node.

**Comment by mwcampbell** [comment]
Please disregard my previous comment. In the cases I had looked at, `self.child` is a `WidgetPod`. So in that case, the `accessibility` implementation on `self.child` does push a child node, and what you're doing is correct.

**Comment by PoignardAzur** [comment]
> Please disregard my previous comment. In the cases I had looked at, `self.child` is a `WidgetPod`. So in that case, the `accessibility` implementation on `self.child` does push a child node, and what you're doing is correct.

Right, in every single case in Masonry when a widget calls another widget's method, it's through WidgetPod. There's actually some code that tries to enforce that.

**Review by DJMcNab — APPROVED** [review]
Approval for process purposes

I've not had time to review this code myself. But it's really good we're getting this working

**Comment by mwcampbell** [comment]
It's OK with me if we merge this now and do further fixes as separate PRs, so we don't have to keep rebasing this one.

**Comment by jaredoconnell** [comment]
I've never used accessessiblity features, so I'm not sure exactly what to test, but if I turn on Windows 10's narrator, the app just crashes. Tested on the `mason` and `calc` examples. It crashes if it's already open, and it crashes if it's opened. The error message is not very descriptive.
The `mason` example does not crash on main.
```
 process didn't exit successfully: `C:\Users\Admin\source\repos\xilem\target\debug\examples\mason.exe` (exit code: 101)
```

What environment are you testing this on?

**Comment by mwcampbell** [comment]
Oh, I hadn't tested the mason example yet. Looking at that now.

**Comment by mwcampbell** [comment]
Yes, I get this panic with the mason example:

```
thread 'main' panicked at C:\Users\mattc\.cargo\registry\src\index.crates.io-6f17d22bba15001f\accesskit_consumer-0.19.0\src\tree.rs:142:9:
assertion `left == right` failed
  left: 5
 right: 0
```

It's panicking on this assertion in `src/tree.rs` in the `accesskit_consumer` crate:

```
assert_eq!(pending_nodes.len(), 0);
```

This happens if you include child nodes in the tree update without adding their IDs to the `children` property of any parent node.

**Comment by mwcampbell** [comment]
If I run the calc example with NVDA already running, the bounding rectangles of all the nodes are set to (0, 0, 0, 0). This suggests that the `InitialTreeRequested` event handler is producing an accessibility tree before layout is done. As I said in chat, it's not strictly necessary to produce the initial tree inside that event handler. That event handler is already running asynchronously, due to a limitation of winit, so AccessKit is already having to use a placeholder tree at first. So it might be better to request a repaint, set some flag indicating that a full accessibility tree is required, and do the accessibility tree update as part of the normal lifecycle. We just have to make sure that the initial tree update is pushed soon, but not necessarily immediately inside that event handler.

**Comment by mwcampbell** [comment]
Is Masonry setting the AccessKit bounding rectangles in physical coordinates? If not, it needs to. If I test with NVDA and move the mouse over the buttons in the calc example, what it speaks doesn't match what's actually under the mouse cursor, suggesting that the bounding rectangles are inaccurate.

**Comment by mwcampbell** [comment]
The role of the root node should be `Role::Window`. As it is now, NVDA and Narrator announce, for example, "Simple Calculator grouping" instead of "Simple Calculator window".

**Pull request merged**
