### PR TITLE
Fix inference of wrapper views

### PR DESCRIPTION
**Pull request by RagibHasin**

### CODE REVIEW

**Review by RagibHasin — COMMENTED** [review]
Fixes `sized_box`. I didn't find any other wrapper views. Is there any?

**Review by DJMcNab — APPROVED** [review]
This looks as expected, thanks.

Does this not fix the inference in the `state_machine` example?
If not, why not?

**Comment by DJMcNab** [comment]
Thank you!

**Comment by Philipp-M** [comment]
I wonder if this would also be necessary for non-wrapping views, but I don't think it is? IIRC I only had issues yet when views either contain a `ViewSequence` or a  `View`.

**Pull request merged**
