### PR TITLE
xilem_html: Add support for non-passive event handlers

### PR DESCRIPTION
**Pull request by jplatte**
Allows adding `.passive(false)` after `.on_click(/* closure */)`. Maybe not the most intuitive but since optional args aren't a thing, I don't have another idea for now.

### CODE REVIEW

**Comment by waywardmonkeys** [comment]
Todomvc should call this, or did you want to do that separately?

**Comment by jplatte** [comment]
Right, didn't think to update the example (actually needed this elsewhere).

**Review by waywardmonkeys — APPROVED** [review]
I think this looks good, but @Philipp-M or someone else should probably review as well.

**Review by Philipp-M — APPROVED** [review]
LGTM.

The design of changing attributes of event listeners (and other "pseudo" views) is also still an open question I think (see also [here](https://github.com/linebender/xilem/pull/103#discussion_r1265698733)).

For now the builder pattern per fine-grained attribute is fine, but I have the feeling that it can get a little bit confusing when overusing the builder pattern (one idea I have in mind is something like [this](https://github.com/Philipp-M/trui/blob/74c46ca985558f6f3129f4a3dd773e00fa5e50ff/src/view/block.rs#L136)). But I guess we should just experiment a little bit to get a feeling about that...

**Pull request merged**
